### ISSUE TITLE
Getting Indexerror

### ISSUE THREAD

**Issue by aryankhatana01** [zenilharia26/Whatsapp-Text-To-JSON#2]
Hi I was using your script and gave it all the necessary arguments but it threw this error:
  File "whatsapp.py", line 48, in <module>
    lines[-1][-1] += '\n ' + line[:-1] #For extra paragraphs or lines in messages.
IndexError: list index out of range

what should i do?

**Comment by zenilharia26** [comment]
Hey, thank you for pointing it out. Actually there are many minor test cases of the input WhatsApp text files for which the code shows an error. I need to configure my code for those files as well.
Meanwhile, I would suggest that you debug your code as to which line in the chat file are you getting this issue.

**Comment by aryankhatana01** [comment]
Thanks for your reply...

**Comment by sedativum** [comment]
I tried running it the exit() wnts to kill the program before I can pass arguments für the cli, how can I fix that?

**Comment by zenilharia26** [comment]
I have added some extra safety features and I think now the error should not persist. If it persists, it will display the line in which the error was found and continue to the next line.
